version: '3'

services:
  bot:
    container_name: bot_image
    image: 192.168.43.65:5000/bot_image
    build: bot/.
    env_file: .env
    volumes:
      - pg_logs:/repl_logs
    networks:
      network_bot:
        ipv4_address: 172.10.0.10

  database:
    container_name: db_image
    image: 192.168.43.65:5000/db_image
    build: db/.
    networks:
      network_bot:
        ipv4_address: ${DB_HOST}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication ${DB_REPL_USER} ${DB_REPL_HOST}/0 trust\nhost all all 0.0.0.0/0 password"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - pg_logs:/var/log/postgres 
    ports:
      - "5432:5432"
    command: |
      postgres
      -c wal_level=replica
      -c listen_addresses='*'
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c logging_collector=on
      -c log_replication_commands=on
      -c log_directory=/var/log/postgres/
      -c log_filename=postgresql.log
      -c archive_mode=on
      -c archive_command='cp %p /oracle/pg_data/archive/%f'
      -c wal_log_hints=on
  db_repl_image:
    container_name: db_repl_image
    image: 192.168.43.65:5000/db_repl_image
    build: db_repl/.
    ports:
      - "5433:5432"
    environment:
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: |
      bash -c "
      sleep 5s
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=${DB_HOST} --port=${DB_PORT} -U ${DB_REPL_USER}
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      su postgres
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - database
    networks:
      network_bot:
        ipv4_address: ${DB_REPL_HOST}
volumes:
  pg_logs:

networks:
  network_bot:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24